services:
    _defaults:
        autoconfigure: true
        autowire: true

    Becklyn\IconLoader\:
        resource: '../../*'

    Becklyn\IconLoader\Registry\IconRegistry:
        $isDebug: '%kernel.debug%'
        $projectDir: '%kernel.project_dir%'
