services:
    _defaults:
        autoconfigure: true
        autowire: true

    Becklyn\IconLoader\:
        resource: '../../*'

    Becklyn\IconLoader\Registry\IconRegistry:
        $cache: '@cache.app'
        $isDebug: '%kernel.debug%'
        $projectDir: '%kernel.project_dir%'
